import { GoogleGenAI } from "@google/genai";
import { Ethnicity, Scene, Vibe } from "../types";

// Helper to convert File to Base64
export const fileToGenerativePart = async (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = reader.result as string;
      // Remove the data URL prefix (e.g., "data:image/jpeg;base64,")
      const base64Data = base64String.split(',')[1];
      resolve(base64Data);
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};

export const generateTryOnImage = async (
  imageBase64: string,
  ethnicity: Ethnicity,
  vibe: Vibe,
  scene: Scene
): Promise<string> => {
  
  // Safely check for API Key without crashing if process is undefined
  const apiKey = (typeof process !== 'undefined' && process.env) ? process.env.API_KEY : null;

  if (!apiKey) {
    throw new Error("API Key is missing. Please ensure process.env.API_KEY is set or use the Google Login feature.");
  }

  const ai = new GoogleGenAI({ apiKey: apiKey });
  
  // Construct a descriptive prompt for the model
  const prompt = `
    Generate a high-quality, photorealistic fashion photograph based on the clothing in the input image.
    
    Instructions:
    1. Identify the main garment in the provided image.
    2. Generate a model wearing this exact garment. The model must be ${ethnicity}.
    3. The model's expression and pose should convey a "${vibe}" personality.
    4. The background location is: ${scene}.
    5. Ensure lighting, shadows, and fabric textures are realistic.
    6. The output should look like a professional fashion magazine shot.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: prompt,
          },
          {
            inlineData: {
              data: imageBase64,
              mimeType: 'image/jpeg', // Assuming jpeg/png, standardizes slightly
            },
          },
        ],
      },
    });

    let imageUrl = '';

    if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                const base64EncodeString = part.inlineData.data;
                imageUrl = `data:image/png;base64,${base64EncodeString}`;
                break;
            }
        }
    }

    if (!imageUrl) {
        throw new Error("No image was generated by the model. Please try again.");
    }

    return imageUrl;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};